/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.wikipedia.miner.extract.model.struct;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PageDetail extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PageDetail\",\"namespace\":\"org.wikipedia.miner.extract.model.struct\",\"fields\":[{\"name\":\"id\",\"type\":[\"int\",\"null\"]},{\"name\":\"title\",\"type\":[\"string\",\"null\"]},{\"name\":\"namespace\",\"type\":[\"int\",\"null\"]},{\"name\":\"lastEdited\",\"type\":[\"long\",\"null\"]},{\"name\":\"isRedirect\",\"type\":\"boolean\"},{\"name\":\"redirectsToTitle\",\"type\":[\"string\",\"null\"]},{\"name\":\"redirectsTo\",\"type\":[{\"type\":\"record\",\"name\":\"PageSummary\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"title\",\"type\":\"string\"},{\"name\":\"namespace\",\"type\":\"int\"},{\"name\":\"forwarded\",\"type\":\"boolean\"},{\"name\":\"backtracked\",\"type\":\"boolean\"}]},\"null\"]},{\"name\":\"redirects\",\"type\":{\"type\":\"array\",\"items\":\"PageSummary\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.Integer id;
  @Deprecated public java.lang.CharSequence title;
  @Deprecated public java.lang.Integer namespace;
  @Deprecated public java.lang.Long lastEdited;
  @Deprecated public boolean isRedirect;
  @Deprecated public java.lang.CharSequence redirectsToTitle;
  @Deprecated public org.wikipedia.miner.extract.model.struct.PageSummary redirectsTo;
  @Deprecated public java.util.List<org.wikipedia.miner.extract.model.struct.PageSummary> redirects;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public PageDetail() {}

  /**
   * All-args constructor.
   */
  public PageDetail(java.lang.Integer id, java.lang.CharSequence title, java.lang.Integer namespace, java.lang.Long lastEdited, java.lang.Boolean isRedirect, java.lang.CharSequence redirectsToTitle, org.wikipedia.miner.extract.model.struct.PageSummary redirectsTo, java.util.List<org.wikipedia.miner.extract.model.struct.PageSummary> redirects) {
    this.id = id;
    this.title = title;
    this.namespace = namespace;
    this.lastEdited = lastEdited;
    this.isRedirect = isRedirect;
    this.redirectsToTitle = redirectsToTitle;
    this.redirectsTo = redirectsTo;
    this.redirects = redirects;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return title;
    case 2: return namespace;
    case 3: return lastEdited;
    case 4: return isRedirect;
    case 5: return redirectsToTitle;
    case 6: return redirectsTo;
    case 7: return redirects;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: title = (java.lang.CharSequence)value$; break;
    case 2: namespace = (java.lang.Integer)value$; break;
    case 3: lastEdited = (java.lang.Long)value$; break;
    case 4: isRedirect = (java.lang.Boolean)value$; break;
    case 5: redirectsToTitle = (java.lang.CharSequence)value$; break;
    case 6: redirectsTo = (org.wikipedia.miner.extract.model.struct.PageSummary)value$; break;
    case 7: redirects = (java.util.List<org.wikipedia.miner.extract.model.struct.PageSummary>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }

  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'namespace' field.
   */
  public java.lang.Integer getNamespace() {
    return namespace;
  }

  /**
   * Sets the value of the 'namespace' field.
   * @param value the value to set.
   */
  public void setNamespace(java.lang.Integer value) {
    this.namespace = value;
  }

  /**
   * Gets the value of the 'lastEdited' field.
   */
  public java.lang.Long getLastEdited() {
    return lastEdited;
  }

  /**
   * Sets the value of the 'lastEdited' field.
   * @param value the value to set.
   */
  public void setLastEdited(java.lang.Long value) {
    this.lastEdited = value;
  }

  /**
   * Gets the value of the 'isRedirect' field.
   */
  public java.lang.Boolean getIsRedirect() {
    return isRedirect;
  }

  /**
   * Sets the value of the 'isRedirect' field.
   * @param value the value to set.
   */
  public void setIsRedirect(java.lang.Boolean value) {
    this.isRedirect = value;
  }

  /**
   * Gets the value of the 'redirectsToTitle' field.
   */
  public java.lang.CharSequence getRedirectsToTitle() {
    return redirectsToTitle;
  }

  /**
   * Sets the value of the 'redirectsToTitle' field.
   * @param value the value to set.
   */
  public void setRedirectsToTitle(java.lang.CharSequence value) {
    this.redirectsToTitle = value;
  }

  /**
   * Gets the value of the 'redirectsTo' field.
   */
  public org.wikipedia.miner.extract.model.struct.PageSummary getRedirectsTo() {
    return redirectsTo;
  }

  /**
   * Sets the value of the 'redirectsTo' field.
   * @param value the value to set.
   */
  public void setRedirectsTo(org.wikipedia.miner.extract.model.struct.PageSummary value) {
    this.redirectsTo = value;
  }

  /**
   * Gets the value of the 'redirects' field.
   */
  public java.util.List<org.wikipedia.miner.extract.model.struct.PageSummary> getRedirects() {
    return redirects;
  }

  /**
   * Sets the value of the 'redirects' field.
   * @param value the value to set.
   */
  public void setRedirects(java.util.List<org.wikipedia.miner.extract.model.struct.PageSummary> value) {
    this.redirects = value;
  }

  /** Creates a new PageDetail RecordBuilder */
  public static org.wikipedia.miner.extract.model.struct.PageDetail.Builder newBuilder() {
    return new org.wikipedia.miner.extract.model.struct.PageDetail.Builder();
  }
  
  /** Creates a new PageDetail RecordBuilder by copying an existing Builder */
  public static org.wikipedia.miner.extract.model.struct.PageDetail.Builder newBuilder(org.wikipedia.miner.extract.model.struct.PageDetail.Builder other) {
    return new org.wikipedia.miner.extract.model.struct.PageDetail.Builder(other);
  }
  
  /** Creates a new PageDetail RecordBuilder by copying an existing PageDetail instance */
  public static org.wikipedia.miner.extract.model.struct.PageDetail.Builder newBuilder(org.wikipedia.miner.extract.model.struct.PageDetail other) {
    return new org.wikipedia.miner.extract.model.struct.PageDetail.Builder(other);
  }
  
  /**
   * RecordBuilder for PageDetail instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PageDetail>
    implements org.apache.avro.data.RecordBuilder<PageDetail> {

    private java.lang.Integer id;
    private java.lang.CharSequence title;
    private java.lang.Integer namespace;
    private java.lang.Long lastEdited;
    private boolean isRedirect;
    private java.lang.CharSequence redirectsToTitle;
    private org.wikipedia.miner.extract.model.struct.PageSummary redirectsTo;
    private java.util.List<org.wikipedia.miner.extract.model.struct.PageSummary> redirects;

    /** Creates a new Builder */
    private Builder() {
      super(org.wikipedia.miner.extract.model.struct.PageDetail.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.wikipedia.miner.extract.model.struct.PageDetail.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.namespace)) {
        this.namespace = data().deepCopy(fields()[2].schema(), other.namespace);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.lastEdited)) {
        this.lastEdited = data().deepCopy(fields()[3].schema(), other.lastEdited);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.isRedirect)) {
        this.isRedirect = data().deepCopy(fields()[4].schema(), other.isRedirect);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.redirectsToTitle)) {
        this.redirectsToTitle = data().deepCopy(fields()[5].schema(), other.redirectsToTitle);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.redirectsTo)) {
        this.redirectsTo = data().deepCopy(fields()[6].schema(), other.redirectsTo);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.redirects)) {
        this.redirects = data().deepCopy(fields()[7].schema(), other.redirects);
        fieldSetFlags()[7] = true;
      }
    }
    
    /** Creates a Builder by copying an existing PageDetail instance */
    private Builder(org.wikipedia.miner.extract.model.struct.PageDetail other) {
            super(org.wikipedia.miner.extract.model.struct.PageDetail.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.namespace)) {
        this.namespace = data().deepCopy(fields()[2].schema(), other.namespace);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.lastEdited)) {
        this.lastEdited = data().deepCopy(fields()[3].schema(), other.lastEdited);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.isRedirect)) {
        this.isRedirect = data().deepCopy(fields()[4].schema(), other.isRedirect);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.redirectsToTitle)) {
        this.redirectsToTitle = data().deepCopy(fields()[5].schema(), other.redirectsToTitle);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.redirectsTo)) {
        this.redirectsTo = data().deepCopy(fields()[6].schema(), other.redirectsTo);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.redirects)) {
        this.redirects = data().deepCopy(fields()[7].schema(), other.redirects);
        fieldSetFlags()[7] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public org.wikipedia.miner.extract.model.struct.PageDetail.Builder setId(java.lang.Integer value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public org.wikipedia.miner.extract.model.struct.PageDetail.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'title' field */
    public java.lang.CharSequence getTitle() {
      return title;
    }
    
    /** Sets the value of the 'title' field */
    public org.wikipedia.miner.extract.model.struct.PageDetail.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.title = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'title' field has been set */
    public boolean hasTitle() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'title' field */
    public org.wikipedia.miner.extract.model.struct.PageDetail.Builder clearTitle() {
      title = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'namespace' field */
    public java.lang.Integer getNamespace() {
      return namespace;
    }
    
    /** Sets the value of the 'namespace' field */
    public org.wikipedia.miner.extract.model.struct.PageDetail.Builder setNamespace(java.lang.Integer value) {
      validate(fields()[2], value);
      this.namespace = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'namespace' field has been set */
    public boolean hasNamespace() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'namespace' field */
    public org.wikipedia.miner.extract.model.struct.PageDetail.Builder clearNamespace() {
      namespace = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'lastEdited' field */
    public java.lang.Long getLastEdited() {
      return lastEdited;
    }
    
    /** Sets the value of the 'lastEdited' field */
    public org.wikipedia.miner.extract.model.struct.PageDetail.Builder setLastEdited(java.lang.Long value) {
      validate(fields()[3], value);
      this.lastEdited = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'lastEdited' field has been set */
    public boolean hasLastEdited() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'lastEdited' field */
    public org.wikipedia.miner.extract.model.struct.PageDetail.Builder clearLastEdited() {
      lastEdited = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'isRedirect' field */
    public java.lang.Boolean getIsRedirect() {
      return isRedirect;
    }
    
    /** Sets the value of the 'isRedirect' field */
    public org.wikipedia.miner.extract.model.struct.PageDetail.Builder setIsRedirect(boolean value) {
      validate(fields()[4], value);
      this.isRedirect = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'isRedirect' field has been set */
    public boolean hasIsRedirect() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'isRedirect' field */
    public org.wikipedia.miner.extract.model.struct.PageDetail.Builder clearIsRedirect() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'redirectsToTitle' field */
    public java.lang.CharSequence getRedirectsToTitle() {
      return redirectsToTitle;
    }
    
    /** Sets the value of the 'redirectsToTitle' field */
    public org.wikipedia.miner.extract.model.struct.PageDetail.Builder setRedirectsToTitle(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.redirectsToTitle = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'redirectsToTitle' field has been set */
    public boolean hasRedirectsToTitle() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'redirectsToTitle' field */
    public org.wikipedia.miner.extract.model.struct.PageDetail.Builder clearRedirectsToTitle() {
      redirectsToTitle = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'redirectsTo' field */
    public org.wikipedia.miner.extract.model.struct.PageSummary getRedirectsTo() {
      return redirectsTo;
    }
    
    /** Sets the value of the 'redirectsTo' field */
    public org.wikipedia.miner.extract.model.struct.PageDetail.Builder setRedirectsTo(org.wikipedia.miner.extract.model.struct.PageSummary value) {
      validate(fields()[6], value);
      this.redirectsTo = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'redirectsTo' field has been set */
    public boolean hasRedirectsTo() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'redirectsTo' field */
    public org.wikipedia.miner.extract.model.struct.PageDetail.Builder clearRedirectsTo() {
      redirectsTo = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'redirects' field */
    public java.util.List<org.wikipedia.miner.extract.model.struct.PageSummary> getRedirects() {
      return redirects;
    }
    
    /** Sets the value of the 'redirects' field */
    public org.wikipedia.miner.extract.model.struct.PageDetail.Builder setRedirects(java.util.List<org.wikipedia.miner.extract.model.struct.PageSummary> value) {
      validate(fields()[7], value);
      this.redirects = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'redirects' field has been set */
    public boolean hasRedirects() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'redirects' field */
    public org.wikipedia.miner.extract.model.struct.PageDetail.Builder clearRedirects() {
      redirects = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    public PageDetail build() {
      try {
        PageDetail record = new PageDetail();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.title = fieldSetFlags()[1] ? this.title : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.namespace = fieldSetFlags()[2] ? this.namespace : (java.lang.Integer) defaultValue(fields()[2]);
        record.lastEdited = fieldSetFlags()[3] ? this.lastEdited : (java.lang.Long) defaultValue(fields()[3]);
        record.isRedirect = fieldSetFlags()[4] ? this.isRedirect : (java.lang.Boolean) defaultValue(fields()[4]);
        record.redirectsToTitle = fieldSetFlags()[5] ? this.redirectsToTitle : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.redirectsTo = fieldSetFlags()[6] ? this.redirectsTo : (org.wikipedia.miner.extract.model.struct.PageSummary) defaultValue(fields()[6]);
        record.redirects = fieldSetFlags()[7] ? this.redirects : (java.util.List<org.wikipedia.miner.extract.model.struct.PageSummary>) defaultValue(fields()[7]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
